[tool.poetry]
name = "cells-kata"
version = "0.1.0"
description = ""
authors = ["Altair J. Fernandes <tatosjb@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^8.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
